server:
  port: 8060


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: agytorudhcv11
    url: jdbc:mysql://localhost:3306/securitydemo?useSSL=false
    username: root

  redis:
    cluster:
      nodes[0]: 127.0.0.1:6379
      nodes[1]: 127.0.0.1:6380
      nodes[2]: 127.0.0.1:6381
      nodes[3]: 127.0.0.1:6382
      nodes[4]: 127.0.0.1:6383
      nodes[5]: 127.0.0.1:6384
      max-redirects: 3
    jedis:
      pool:
        max-active: 8
        min-idle: 0