server:
  port: 8060


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: agytorudhcv11
    url: jdbc:mysql://localhost:3306/xiyou3g_middle_ware?useSSL=false
    username: root
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        min-idle: 2

